homepage:
    path: /
    controller: App\Controller\RegistrationController::register
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_offers_table:
    path: /dashboard/offers
    controller: App\Controller\DashboardController::offersTable
